/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.seeseemelk.jxe;

import java.io.IOException;
import java.nio.file.Paths;

import be.seeseemelk.jxe.recompiler.Recompiler;

public class App
{

	public static void main(String[] args) throws IOException
	{
		if (args.length > 0)
		{
			for (var arg : args)
				new Recompiler(Paths.get(arg), Paths.get("output")).recompile();
		}
		else
		{
			var recompiler = new Recompiler(Paths.get("input"), Paths.get("output"));
			recompiler.recompile();
		}
	}
}
